### ISSUE TITLE
!comment not centered in figure when using shared columns

### ISSUE THREAD

**Issue by SECtim** [webhamster/annexlang#16]
tl;dr: Parties that share a column must be defined "at once", i.e., without other parties in between (in the `parties` list). Otherwise, `!comment`s will not be correctly placed.

The comment in the following yml is centered on the "B" party, not on the whole figure. The same happens when "A" is not started/ended at all.
```yml
protocol:
  !Protocol
  parties:
  - &a
    !Party
    name: 'A'
  - &c
    !Party
    name: 'C'
  - &b
    !Party
    name: 'B'
    column: *a

  steps:
    - !Parallel
      steps:
        - !start-party
          party: *c
        - !start-party
          party: *b
    - !comment
      label: 'Some text'
    - !end-party
      party: *b
    - !start-party
     party: *a
    - !Parallel
      steps:
        - !end-party
          party: *c
        - !end-party
          party: *a
```
Result:
![Image](https://github.com/user-attachments/assets/aff9d6af-4235-42dd-8581-09a784768beb)

Whereas, if I define party B _immediately_ after party A, everything works as expected, i.e., with the `parties` list as
```yml
  parties:
  - &a
    !Party
    name: 'A'
  - &b
    !Party
    name: 'B'
    column: *a
  - &c
    !Party
    name: 'C'
```
I get

![Image](https://github.com/user-attachments/assets/d8c15a42-49c9-45dc-acd3-80ac2a7d7235)

Adding yet another party (at the end of the party list):
```yml
  - &d
    !Party
    name: 'D'
    column: *a
```
that is never referenced in the protocol re-introduces the issue. And as before, if that party D is defined _immediately_ after A or B, everything works as expected.
